# https://nixpacks.com/docs/configuration/file
# настройка переменных для минимизации неудобств
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # отключить уведомления об обновлениях
    NPM_CONFIG_FUND = 'false' # отключить уведомления о финансировании

# загрузить caddy из nix
[phases.caddy]
    dependsOn = ['setup'] # этот этап выполняется после этапа 'setup'
    nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301' # Caddy v2.8.4
    nixPkgs = ['caddy'] # установить caddy как nix пакет

# форматировать Caddyfile
[phases.fmt]
    dependsOn = ['caddy'] # этот этап выполняется после этапа 'caddy'
    cmds = ['caddy fmt --overwrite Caddyfile'] # форматировать Caddyfile для исправления несоответствий

# запустить веб-сервер caddy
[start]
    cmd = 'exec caddy run --config Caddyfile --adapter caddyfile 2>&1' # запуск caddy с использованием Caddyfile
